project:
  type: website

website:
  title: "Posts by Rito Ghosh"
  site-url: https://ghosh-r.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ritog
      - icon: twitter
        href: https://twitter.com/AllesistKode
      - icon: rss
        href: index.xml
format:
  html:
    theme: solar
    monofont: "Cascadia Code PL"
    css: styles.css

execute:
    freeze: auto

