project:
  type: website

website:
  title: "Posts by Rito Ghosh"
  site-url: https://ritog.github.io
  search: true
  comments:
    utterances:
      repo: ritog/ritog.github.io
      label: comment-utter
      theme: github-dark
  navbar:
    right:
      - about.qmd
      - now.qmd
      - cv.qmd
      - publications.qmd
      - text: "{{< iconify fa6-brands github >}}"
        href: https://github.com/ritog
      - text: "{{< iconify fa6-brands x-twitter >}}"
        href: https://twitter.com/AllesistKode
      - text: "{{< iconify fa6-brands google-scholar >}}"
        href: https://scholar.google.com/citations?user=R_X74h0AAAAJ
      - text: "{{< iconify fa6-brands mastodon >}}"
        href: https://mathstodon.xyz/@rg
        rel: me
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: https://linkedin.com/in/ritobrata-ghosh
      - icon: rss
        href: index.xml
    left:
      - TILs_index.qmd
format:
  html:
    theme:
      dark: solar
      light: lumen
    monofont: "Cascadia Code"
    css: styles.css
    anchor-sections: true
    mainfont: "IBM Plex Mono"
    code-line-numbers: true
    code-copy: true
    linkcolor: "cyan"


execute:
    freeze: auto
