project:
  type: website

website:
  title: "Posts by Rito Ghosh"
  site-url: https://ritog.github.io
  navbar:
    right:
      - about.qmd
      - cv.qmd
      - icon: github
        href: https://github.com/ritog
      - icon: twitter
        href: https://twitter.com/AllesistKode
      - icon: google-scholar
        text: Google Scholar
        href: https://scholar.google.com/citations?user=R_X74h0AAAAJ
      - icon: rss
        href: index.xml
format:
  html:
    theme: solar
    monofont: "Cascadia Code PL"
    css: styles.css

execute:
    freeze: auto

