project:
  type: website

website:
  title: "Posts by Rito Ghosh"
  site-url: https://ritog.github.io
  search: true
  navbar:
    right:
      - about.qmd
      - cv.qmd
      - icon: github
        href: https://github.com/ritog
      - icon: twitter
        href: https://twitter.com/AllesistKode
      - text: "{{< iconify fa6-brands google-scholar >}}"
        href: https://scholar.google.com/citations?user=R_X74h0AAAAJ
      - icon: rss
        href: index.xml
format:
  html:
    theme: solar
    monofont: "Cascadia Code"
    css: styles.css
    anchor-sections: true
    mainfont: "IBM Plex Sans"
    monobackgroundcolor: "black"
    code-line-numbers: true
    code-copy: true
    code-block-bg: "black"
    fontsize: 1.4em


execute:
    freeze: auto

